<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyTitle>CataTweaks</AssemblyTitle>
    <Version>3.2.0</Version>
    <GameDir Condition="'$(GameDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Terra Invicta</GameDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="test\**" />
    <Compile Remove="tools\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp" HintPath="$(GameDir)\TerraInvicta_Data\Managed\Assembly-CSharp.dll" Private="false" />
    <Reference Include="UnityEngine" HintPath="$(GameDir)\TerraInvicta_Data\Managed\UnityEngine.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(GameDir)\TerraInvicta_Data\Managed\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.JSONSerializeModule" HintPath="$(GameDir)\TerraInvicta_Data\Managed\UnityEngine.JSONSerializeModule.dll" Private="false" />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="$(GameDir)\TerraInvicta_Data\Managed\UnityEngine.TextRenderingModule.dll" Private="false" />
    <Reference Include="UnityEngine.UIModule" HintPath="$(GameDir)\TerraInvicta_Data\Managed\UnityEngine.UIModule.dll" Private="false" />
    <Reference Include="UnityEngine.IMGUIModule" HintPath="$(GameDir)\TerraInvicta_Data\Managed\UnityEngine.IMGUIModule.dll" Private="false" />
    <Reference Include="UnityEngine.VideoModule" HintPath="$(GameDir)\TerraInvicta_Data\Managed\UnityEngine.VideoModule.dll" Private="false" />
    <Reference Include="UnityEngine.UI" HintPath="$(GameDir)\TerraInvicta_Data\Managed\UnityEngine.UI.dll" Private="false" />
    <Reference Include="Unity.TextMeshPro" HintPath="$(GameDir)\TerraInvicta_Data\Managed\Unity.TextMeshPro.dll" Private="false" />
    <Reference Include="UnityModManager" HintPath="$(GameDir)\TerraInvicta_Data\Managed\UnityModManager\UnityModManager.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="$(GameDir)\TerraInvicta_Data\Managed\UnityModManager\0Harmony.dll" Private="false" />
  </ItemGroup>
</Project>

